# General server configuration
SERVER_VERSION = 2
PORT_FILE = "myport.info"
DEFAULT_PORT = 1357
MAX_CONNECTIONS = 100
HEADER_SIZE = 23

# Request/Response data sizes
CLIENT_ID_SIZE: int = 16
USERNAME_SIZE: int = 255
PUBLIC_KEY_SIZE: int = 160
MESSAGE_TYPE_BYTES: int = 1
CONTENT_LENGTH_BYTES: int = 4
MESSAGE_HEADER_SIZE: int = CLIENT_ID_SIZE + MESSAGE_TYPE_BYTES + CONTENT_LENGTH_BYTES